# Generated by Django 3.0.7 on 2020-08-26 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
            ],
        ),
        migrations.AddField(
            model_name='сandidate',
            name='sensei',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academy.Jedi'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
                ('visible', models.BooleanField(default=False)),
                ('choice', models.ManyToManyField(to='academy.Choice')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Choice')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Сandidate')),
                ('qestions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Question')),
            ],
        ),
    ]
