# Generated by Django 3.1 on 2020-08-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
