# Generated by Django 3.0.7 on 2020-08-26 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_auto_20200826_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сandidate',
            name='sensei',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academy.Jedi'),
        ),
    ]
