# Generated by Django 3.1 on 2020-08-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_auto_20200824_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='сandidate',
            name='qestions',
            field=models.ManyToManyField(to='academy.Question'),
        ),
    ]
