# Generated by Django 3.1 on 2020-08-24 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_сandidate_qestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.сandidate')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.choice')),
                ('qestions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.question')),
            ],
        ),
    ]
