# Generated by Django 3.0.7 on 2020-08-26 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_auto_20200826_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('max_count_padavans', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AlterField(
            model_name='jedi',
            name='grade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='academy.Grade'),
        ),
    ]
