# Generated by Django 3.1 on 2020-08-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сandidate',
            name='qestions',
        ),
    ]
