# Generated by Django 3.0.7 on 2020-08-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_auto_20200826_2328'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('title',)},
        ),
    ]
