# Generated by Django 3.0.7 on 2020-08-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_auto_20200826_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='jedi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jedi/'),
        ),
        migrations.AddField(
            model_name='сandidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate/'),
        ),
    ]
