# Generated by Django 3.0.7 on 2020-08-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_auto_20200827_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сandidate',
            name='image',
            field=models.ImageField(null=True, upload_to='candidate/'),
        ),
    ]
