# Generated by Django 3.0.7 on 2020-08-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_auto_20200827_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jedi',
            name='image',
        ),
        migrations.RemoveField(
            model_name='сandidate',
            name='image',
        ),
    ]
