# Generated by Django 3.0.7 on 2020-08-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0018_auto_20200831_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='сandidate',
            old_name='sensei',
            new_name='jedi',
        ),
    ]
