# Generated by Django 3.0.7 on 2020-08-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0020_remove_jedi_count_padavans'),
    ]

    operations = [
        migrations.AddField(
            model_name='jedi',
            name='count_padavans',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
