# Generated by Django 3.0.7 on 2020-08-31 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0022_auto_20200831_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jedi',
            name='count_padavans',
        ),
        migrations.AlterField(
            model_name='сandidate',
            name='jedi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='count_padavans', to='academy.Jedi'),
        ),
    ]
