# Generated by Django 3.0.7 on 2020-08-31 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0023_auto_20200831_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='jedi',
            name='count_padavans',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='сandidate',
            name='jedi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensei', to='academy.Jedi'),
        ),
    ]
