# Generated by Django 3.0.7 on 2020-08-31 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0024_auto_20200831_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jedi',
            name='count_padavans',
        ),
    ]
