# Generated by Django 3.0.7 on 2020-08-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0025_remove_jedi_count_padavans'),
    ]

    operations = [
        migrations.AddField(
            model_name='сandidate',
            name='answered_questions',
            field=models.BooleanField(default=False),
        ),
    ]
